name: hitbeat
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  animated_size_and_fade: ^5.1.1
  audio_metadata_reader: ^1.4.2
  audio_service: ^0.18.18
  audio_service_mpris: ^0.2.0
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  collection: ^1.19.1
  cross_file: ^0.3.5
  crypto: ^3.0.7
  cupertino_icons: ^1.0.8
  drift: ^2.29.0
  equatable: ^2.0.7
  file_picker: ^10.3.3
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_modular: ^6.4.1
  interactive_slider: ^0.5.1
  just_audio: ^0.10.5
  just_audio_media_kit: ^2.1.0
  lottie: ^3.3.2
  marquee: ^2.3.0
  media_kit_libs_linux: ^1.2.1
  media_kit_libs_macos_audio: ^1.1.4
  media_kit_libs_windows_audio: ^1.0.9
  menubar:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/menubar
      ref: 12decbe0f592e14e03223f6f2c0c7e0e2dbd70a1
  path: ^1.9.1
  path_provider: ^2.1.5
  rxdart: ^0.28.0
  sidebarx:
    git:
      url: https://github.com/mrhaubrich/sidebarx.git
  sqlite3_flutter_libs: ^0.5.40
  super_context_menu: ^0.9.1
  super_drag_and_drop: ^0.9.1

dev_dependencies:
  build_runner: ^2.10.1
  drift_dev: ^2.29.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
